import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  let header = (
    <header className="blog-header">
      <Link href="/" className="header-link">
        <h1>My Blog</h1>
      </Link>
    </header>
  )

  let footer = (
    <footer>
      <p>© 2026 My Blog</p>
    </footer>
  )

  return (
    <html lang="en">
      <body className="{inter.className}">
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
